<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->insert
        (
            [
            // Bengo
            ['id' => 1, 'Nome' => 'Ambriz', 'provincia_id' => 1],
            ['id' => 2, 'Nome' => 'Bula Atumba', 'provincia_id' => 1],
            ['id' => 3, 'Nome' => 'Dande', 'provincia_id' => 1],
            ['id' => 4, 'Nome' => 'Dembos', 'provincia_id' => 1],
            ['id' => 5, 'Nome' => 'Nambuangongo', 'provincia_id' => 1],
            ['id' => 6, 'Nome' => 'Pango Aluquém', 'provincia_id' => 1],
            ['id' => 7, 'Nome' => 'Quibaxe', 'provincia_id' => 1],
            ['id' => 8, 'Nome' => 'Quitexe', 'provincia_id' => 1],
            ['id' => 9, 'Nome' => 'Uíge', 'provincia_id' => 1],
            // Benguela
            ['id' => 10, 'Nome' => 'Baía Farta', 'provincia_id' => 2],
            ['id' => 11, 'Nome' => 'Balombo', 'provincia_id' => 2],
            ['id' => 12, 'Nome' => 'Benguela', 'provincia_id' => 2],
            ['id' => 13, 'Nome' => 'Bocoio', 'provincia_id' => 2],
            ['id' => 14, 'Nome' => 'Caimbambo', 'provincia_id' => 2],
            ['id' => 15, 'Nome' => 'Catumbela', 'provincia_id' => 2],
            ['id' => 16, 'Nome' => 'Chongoroi', 'provincia_id' => 2],
            ['id' => 17, 'Nome' => 'Cubal', 'provincia_id' => 2],
            ['id' => 18, 'Nome' => 'Ganda', 'provincia_id' => 2],
            ['id' => 19, 'Nome' => 'Lobito', 'provincia_id' => 2],
            ['id' => 20, 'Nome' => 'Cubal', 'provincia_id' => 2],
            // Bié
            ['id' => 21, 'Nome' => 'Andulo', 'provincia_id' => 3],
            ['id' => 22, 'Nome' => 'Camacupa', 'provincia_id' => 3],
            ['id' => 23, 'Nome' => 'Catabola', 'provincia_id' => 3],
            ['id' => 24, 'Nome' => 'Chinguar', 'provincia_id' => 3],
            ['id' => 25, 'Nome' => 'Chitembo', 'provincia_id' => 3],
            ['id' => 26, 'Nome' => 'Cuemba', 'provincia_id' => 3],
            ['id' => 27, 'Nome' => 'Cuito', 'provincia_id' => 3],
            ['id' => 28, 'Nome' => 'Cunhinga', 'provincia_id' => 3],
            ['id' => 29, 'Nome' => 'Nharea', 'provincia_id' => 3],
            ['id' => 30, 'Nome' => 'Nhârea', 'provincia_id' => 3],
            ['id' => 31, 'Nome' => 'Cunhinga', 'provincia_id' => 3],
            // Cabinda
            ['id' => 32, 'Nome' => 'Belize', 'provincia_id' => 4],
            ['id' => 33, 'Nome' => 'Buco-Zau', 'provincia_id' => 4],
            ['id' => 34, 'Nome' => 'Cabinda', 'provincia_id' => 4],
            ['id' => 35, 'Nome' => 'Cacongo', 'provincia_id' => 4],
            ['id' => 36, 'Nome' => 'Landana', 'provincia_id' => 4],
            ['id' => 37, 'Nome' => 'Lândana', 'provincia_id' => 4],
            // Cuando Cubango
            ['id' => 38, 'Nome' => 'Calai', 'provincia_id' => 5],
            ['id' => 39, 'Nome' => 'Cuangar', 'provincia_id' => 5],
            ['id' => 40, 'Nome' => 'Cuchi', 'provincia_id' => 5],
            ['id' => 41, 'Nome' => 'Cuito Cuanavale', 'provincia_id' => 5],
            ['id' => 42, 'Nome' => 'Dirico', 'provincia_id' => 5],
            ['id' => 43, 'Nome' => 'Menongue', 'provincia_id' => 5],
            ['id' => 44, 'Nome' => 'Mavinga', 'provincia_id' => 5],
            ['id' => 45, 'Nome' => 'Nancova', 'provincia_id' => 5],
            ['id' => 46, 'Nome' => 'Rivungo', 'provincia_id' => 5],
            // Cuanza Norte
            ['id' => 47, 'Nome' => 'Ambaca', 'provincia_id' => 6],
            ['id' => 48, 'Nome' => 'Banga', 'provincia_id' => 6],
            ['id' => 49, 'Nome' => 'Bolongongo', 'provincia_id' => 6],
            ['id' => 50, 'Nome' => 'Cambambe', 'provincia_id' => 6],
            ['id' => 51, 'Nome' => 'Cazengo', 'provincia_id' => 6],
            ['id' => 52, 'Nome' => 'Golungo Alto', 'provincia_id' => 6],
            ['id' => 53, 'Nome' => 'Gonguembo', 'provincia_id' => 6],
            ['id' => 54, 'Nome' => 'Lucala', 'provincia_id' => 6],
            ['id' => 55, 'Nome' => 'Quiculungo', 'provincia_id' => 6],
            ['id' => 56, 'Nome' => 'Samba Caju', 'provincia_id' => 6],
            ['id' => 57, 'Nome' => 'Uíge', 'provincia_id' => 6],
            // Cuanza Sul
            ['id' => 58, 'Nome' => 'Amboim', 'provincia_id' => 7],
            ['id' => 59, 'Nome' => 'Cassongue', 'provincia_id' => 7],
            ['id' => 60, 'Nome' => 'Conda', 'provincia_id' => 7],
            ['id' => 61, 'Nome' => 'Ebo', 'provincia_id' => 7],
            ['id' => 62, 'Nome' => 'Gabela', 'provincia_id' => 7],
            ['id' => 63, 'Nome' => 'Libolo', 'provincia_id' => 7],
            ['id' => 64, 'Nome' => 'Mussende', 'provincia_id' => 7],
            ['id' => 65, 'Nome' => 'Porto Amboim', 'provincia_id' => 7],
            ['id' => 66, 'Nome' => 'Quibala', 'provincia_id' => 7],
            ['id' => 67, 'Nome' => 'Quilenda', 'provincia_id' => 7],
            ['id' => 68, 'Nome' => 'Seles', 'provincia_id' => 7],
            ['id' => 69, 'Nome' => 'Sumbe', 'provincia_id' => 7],
            // Cunene
            ['id' => 70, 'Nome' => 'Cahama', 'provincia_id' => 8],
            ['id' => 71, 'Nome' => 'Cuanhama', 'provincia_id' => 8],
            ['id' => 72, 'Nome' => 'Curoca', 'provincia_id' => 8],
            ['id' => 73, 'Nome' => 'Cuvelai', 'provincia_id' => 8],
            ['id' => 74, 'Nome' => 'Namakunde', 'provincia_id' => 8],
            ['id' => 75, 'Nome' => 'Ombadja', 'provincia_id' => 8],
            ['id' => 76, 'Nome' => 'Ondjiva', 'provincia_id' => 8],
            ['id' => 77, 'Nome' => 'Cuanhama', 'provincia_id' => 8],
            ['id' => 78, 'Nome' => 'Ombadja', 'provincia_id' => 8],
            // Huambo
            ['id' => 79, 'Nome' => 'Bailundo', 'provincia_id' => 9],
            ['id' => 80, 'Nome' => 'Caála', 'provincia_id' => 9],
            ['id' => 81, 'Nome' => 'Catchiungo', 'provincia_id' => 9],
            ['id' => 82, 'Nome' => 'Chicala-Cholohanga', 'provincia_id' => 9],
            ['id' => 83, 'Nome' => 'Chinjenje', 'provincia_id' => 9],
            ['id' => 84, 'Nome' => 'Longonjo', 'provincia_id' => 9],
            ['id' => 85, 'Nome' => 'Huambo', 'provincia_id' => 9],
            ['id' => 86, 'Nome' => 'Londuimbali', 'provincia_id' => 9],
            ['id' => 87, 'Nome' => 'Mungo', 'provincia_id' => 9],
            ['id' => 88, 'Nome' => 'Tchicala-Tcholohanga', 'provincia_id' => 9],
            ['id' => 89, 'Nome' => 'Tchindjenje', 'provincia_id' => 9],
            ['id' => 90, 'Nome' => 'Ucuma', 'provincia_id' => 9],
            // Huíla
            ['id' => 91, 'Nome' => 'Caconda', 'provincia_id' => 10],
            ['id' => 92, 'Nome' => 'Caíla', 'provincia_id' => 10],
            ['id' => 93, 'Nome' => 'Caluquembe', 'provincia_id' => 10],
            ['id' => 94, 'Nome' => 'Chiange', 'provincia_id' => 10],
            ['id' => 95, 'Nome' => 'Chibia', 'provincia_id' => 10],
            ['id' => 96, 'Nome' => 'Chicomba', 'provincia_id' => 10],
            ['id' => 97, 'Nome' => 'Chipindo', 'provincia_id' => 10],
            ['id' => 98, 'Nome' => 'Cuvango', 'provincia_id' => 10],
            ['id' => 99, 'Nome' => 'Gambos', 'provincia_id' => 10],
            ['id' => 100, 'Nome' => 'Humpata', 'provincia_id' => 10],
            ['id' => 101, 'Nome' => 'Lubango', 'provincia_id' => 10],
            // Luanda
            ['id' => 102, 'Nome' => 'Belas', 'provincia_id' => 11],
            ['id' => 103, 'Nome' => 'Cacuaco', 'provincia_id' => 11],
            ['id' => 104, 'Nome' => 'Cazenga', 'provincia_id' => 11],
            ['id' => 105, 'Nome' => 'Ícolo e Bengo', 'provincia_id' => 11],
            ['id' => 106, 'Nome' => 'Luanda', 'provincia_id' => 11],
            ['id' => 107, 'Nome' => 'Quiçama', 'provincia_id' => 11],
            ['id' => 108, 'Nome' => 'Quissama', 'provincia_id' => 11],
            ['id' => 109, 'Nome' => 'Talatona', 'provincia_id' => 11],
            // Lunda Norte
            ['id' => 110, 'Nome' => 'Cambulo', 'provincia_id' => 12],
            ['id' => 111, 'Nome' => 'Capenda-Camulemba', 'provincia_id' => 12],
            ['id' => 112, 'Nome' => 'Caungula', 'provincia_id' => 12],
            ['id' => 113, 'Nome' => 'Chitato', 'provincia_id' => 12],
            ['id' => 114, 'Nome' => 'Cuango', 'provincia_id' => 12],
            ['id' => 115, 'Nome' => 'Cuílo', 'provincia_id' => 12],
            ['id' => 116, 'Nome' => 'Lóvua', 'provincia_id' => 12],
            ['id' => 117, 'Nome' => 'Lunda', 'provincia_id' => 12],
            ['id' => 118, 'Nome' => 'Lubalo', 'provincia_id' => 12],
            // Lunda Sul
            ['id' => 119, 'Nome' => 'Cacolo', 'provincia_id' => 13],
            ['id' => 120, 'Nome' => 'Dala', 'provincia_id' => 13],
            ['id' => 121, 'Nome' => 'Muconda', 'provincia_id' => 13],
            ['id' => 122, 'Nome' => 'Saurimo', 'provincia_id' => 13],
            ['id' => 123, 'Nome' => 'Lumbala Nguimbo', 'provincia_id' => 13],
            ['id' => 124, 'Nome' => 'Lumeje', 'provincia_id' => 13],
            // Malanje
            ['id' => 125, 'Nome' => 'Cacuso', 'provincia_id' => 14],
            ['id' => 126, 'Nome' => 'Calandula', 'provincia_id' => 14],
            ['id' => 127, 'Nome' => 'Cambundi-Catembo', 'provincia_id' => 14],
            ['id' => 128, 'Nome' => 'Cangandala', 'provincia_id' => 14],
            ['id' => 129, 'Nome' => 'Caombo', 'provincia_id' => 14],
            ['id' => 130, 'Nome' => 'Cuaba Nzoji', 'provincia_id' => 14],
            ['id' => 131, 'Nome' => 'Cunda-Dia-Baze', 'provincia_id' => 14],
            ['id' => 132, 'Nome' => 'Luquembo', 'provincia_id' => 14],
            ['id' => 133, 'Nome' => 'Malanje', 'provincia_id' => 14],
            ['id' => 134, 'Nome' => 'Marimba', 'provincia_id' => 14],
            ['id' => 135, 'Nome' => 'Massango', 'provincia_id' => 14],
            ['id' => 136, 'Nome' => 'Mucari', 'provincia_id' => 14],
            ['id' => 137, 'Nome' => 'Quela', 'provincia_id' => 14],
            ['id' => 138, 'Nome' => 'Quirima', 'provincia_id' => 14],
            ['id' => 139, 'Nome' => 'Techongolola', 'provincia_id' => 14],
            // Moxico
            ['id' => 140, 'Nome' => 'Alto Zambeze', 'provincia_id' => 15],
            ['id' => 141, 'Nome' => 'Bundas', 'provincia_id' => 15],
            ['id' => 142, 'Nome' => 'Cameia', 'provincia_id' => 15],
            ['id' => 143, 'Nome' => 'Luacano', 'provincia_id' => 15],
            ['id' => 144, 'Nome' => 'Luchazes', 'provincia_id' => 15],
            ['id' => 145, 'Nome' => 'Luena', 'provincia_id' => 15],
            ['id' => 146, 'Nome' => 'Lumeje', 'provincia_id' => 15],
            ['id' => 147, 'Nome' => 'Lutembo', 'provincia_id' => 15],
            ['id' => 148, 'Nome' => 'Moxico', 'provincia_id' => 15],
            // Namibe
            ['id' => 149, 'Nome' => 'Bibala', 'provincia_id' => 16],
            ['id' => 150, 'Nome' => 'Camacuio', 'provincia_id' => 16],
            ['id' => 151, 'Nome' => 'Moçâmedes', 'provincia_id' => 16],
            ['id' => 152, 'Nome' => 'Tômbwa', 'provincia_id' => 16],
            // Uíge
            ['id' => 153, 'Nome' => 'Ambuíla', 'provincia_id' => 17],
            ['id' => 154, 'Nome' => 'Bembe', 'provincia_id' => 17],
            ['id' => 155, 'Nome' => 'Buengas', 'provincia_id' => 17],
            ['id' => 156, 'Nome' => 'Bungo', 'provincia_id' => 17],
            ['id' => 157, 'Nome' => 'Damba', 'provincia_id' => 17],
            ['id' => 158, 'Nome' => 'Maquela do Zombo', 'provincia_id' => 17],
            ['id' => 159, 'Nome' => 'Mucaba', 'provincia_id' => 17],
            ['id' => 160, 'Nome' => 'Negage', 'provincia_id' => 17],
            ['id' => 161, 'Nome' => 'Puri', 'provincia_id' => 17],
            ['id' => 162, 'Nome' => 'Quimbele', 'provincia_id' => 17],
            ['id' => 163, 'Nome' => 'Sanza Pombo', 'provincia_id' => 17],
            ['id' => 164, 'Nome' => 'Songo', 'provincia_id' => 17],
            ['id' => 165, 'Nome' => 'Uige', 'provincia_id' => 17],
            // Zaire
            ['id' => 166, 'Nome' => 'Cuimba', 'provincia_id' => 18],
            ['id' => 167, 'Nome' => "M'banza Congo", 'provincia_id' => 18],
            ['id' => 168, 'Nome' => "N'zeto", 'provincia_id' => 18],
            ['id' => 169, 'Nome' => 'Noqui', 'provincia_id' => 18],
            ['id' => 170, 'Nome' => 'Soyo', 'provincia_id' => 18],
         ]
        );
    }
}
