<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('paises')->insert([
            ['codigo' => 'BR', 'pais' => 'Brasil', 'nacionalidade' => 'Brasileira', 'moeda' => 'BRL', 'capital' => 'Brasília', 'latitude' => '-15.7801', 'longitude' => '-47.9292'],
            ['codigo' => 'US', 'pais' => 'Estados Unidos', 'nacionalidade' => 'Americana', 'moeda' => 'USD', 'capital' => 'Washington, D.C.', 'latitude' => '38.8951', 'longitude' => '-77.0367'],
            ['codigo' => 'IN', 'pais' => 'Índia', 'nacionalidade' => 'Indiana', 'moeda' => 'INR', 'capital' => 'Nova Deli', 'latitude' => '28.6139', 'longitude' => '77.2090'],
            ['codigo' => 'CN', 'pais' => 'China', 'nacionalidade' => 'Chinesa', 'moeda' => 'CNY', 'capital' => 'Pequim', 'latitude' => '39.9042', 'longitude' => '116.4074'],
            ['codigo' => 'RU', 'pais' => 'Rússia', 'nacionalidade' => 'Russa', 'moeda' => 'RUB', 'capital' => 'Moscou', 'latitude' => '55.7558', 'longitude' => '37.6176'],
            ['codigo' => 'NG', 'pais' => 'Nigéria', 'nacionalidade' => 'Nigeriana', 'moeda' => 'NGN', 'capital' => 'Abuja', 'latitude' => '9.0579', 'longitude' => '7.4951'],
            ['codigo' => 'ZA', 'pais' => 'África do Sul', 'nacionalidade' => 'Sul-Africana', 'moeda' => 'ZAR', 'capital' => 'Cidade do Cabo', 'latitude' => '-33.9258', 'longitude' => '18.4232'],
            ['codigo' => 'AU', 'pais' => 'Austrália', 'nacionalidade' => 'Australiana', 'moeda' => 'AUD', 'capital' => 'Canberra', 'latitude' => '-35.2809', 'longitude' => '149.1300'],
            ['codigo' => 'AR', 'pais' => 'Argentina', 'nacionalidade' => 'Argentina', 'moeda' => 'ARS', 'capital' => 'Buenos Aires', 'latitude' => '-34.6118', 'longitude' => '-58.4173'],
            ['codigo' => 'FR', 'pais' => 'França', 'nacionalidade' => 'Francesa', 'moeda' => 'EUR', 'capital' => 'Paris', 'latitude' => '48.8566', 'longitude' => '2.3522'],
            ['codigo' => 'DE', 'pais' => 'Alemanha', 'nacionalidade' => 'Alemã', 'moeda' => 'EUR', 'capital' => 'Berlim', 'latitude' => '52.5200', 'longitude' => '13.4050'],
            ['codigo' => 'JP', 'pais' => 'Japão', 'nacionalidade' => 'Japonesa', 'moeda' => 'JPY', 'capital' => 'Tóquio', 'latitude' => '35.6895', 'longitude' => '139.6917'],
            ['codigo' => 'CA', 'pais' => 'Canadá', 'nacionalidade' => 'Canadense', 'moeda' => 'CAD', 'capital' => 'Ottawa', 'latitude' => '45.4215', 'longitude' => '-75.6993'],
            ['codigo' => 'MX', 'pais' => 'México', 'nacionalidade' => 'Mexicana', 'moeda' => 'MXN', 'capital' => 'Cidade do México', 'latitude' => '19.4326', 'longitude' => '-99.1332'],
            ['codigo' => 'IT', 'pais' => 'Itália', 'nacionalidade' => 'Italiana', 'moeda' => 'EUR', 'capital' => 'Roma', 'latitude' => '41.9028', 'longitude' => '12.4964'],
            ['codigo' => 'AO', 'pais' => 'Angola', 'nacionalidade' => 'Angolana', 'moeda' => 'AOA', 'capital' => 'Luanda', 'latitude' => '-8.8383', 'longitude' => '13.2344'],
            ['codigo' => 'KE', 'pais' => 'Quênia', 'nacionalidade' => 'Queniana', 'moeda' => 'KES', 'capital' => 'Nairobi', 'latitude' => '-1.286389', 'longitude' => '36.817223'],
            ['codigo' => 'ET', 'pais' => 'Etiópia', 'nacionalidade' => 'Etíope', 'moeda' => 'ETB', 'capital' => 'Adis Abeba', 'latitude' => '9.1450', 'longitude' => '40.4897'],
            ['codigo' => 'GH', 'pais' => 'Gana', 'nacionalidade' => 'Ganesa', 'moeda' => 'GHS', 'capital' => 'Acra', 'latitude' => '5.6037', 'longitude' => '-0.1870'],
            ['codigo' => 'CD', 'pais' => 'República Democrática do Congo', 'nacionalidade' => 'Congolês', 'moeda' => 'CDF', 'capital' => 'Kinshasa', 'latitude' => '-4.4419', 'longitude' => '15.2663'],
            ['codigo' => 'SD', 'pais' => 'Sudão', 'nacionalidade' => 'Sudanesa', 'moeda' => 'SDG', 'capital' => 'Cartum', 'latitude' => '15.5007', 'longitude' => '32.5599'],
            ['codigo' => 'MA', 'pais' => 'Marrocos', 'nacionalidade' => 'Marroquina', 'moeda' => 'MAD', 'capital' => 'Rabat', 'latitude' => '33.9716', 'longitude' => '-6.8498'],
            ['codigo' => 'MZ', 'pais' => 'Moçambique', 'nacionalidade' => 'Moçambicana', 'moeda' => 'MZN', 'capital' => 'Maputo', 'latitude' => '-25.9667', 'longitude' => '32.5831'],
            ['codigo' => 'CI', 'pais' => 'Costa do Marfim', 'nacionalidade' => 'Marfinense', 'moeda' => 'XOF', 'capital' => 'Yamoussoukro', 'latitude' => '6.8277', 'longitude' => '-5.2893'],
            ['codigo' => 'UG', 'pais' => 'Uganda', 'nacionalidade' => 'Ugandense', 'moeda' => 'UGX', 'capital' => 'Campala', 'latitude' => '0.3136', 'longitude' => '32.5811'],
            ['codigo' => 'TN', 'pais' => 'Tunísia', 'nacionalidade' => 'Tunisiana', 'moeda' => 'TND', 'capital' => 'Túnis', 'latitude' => '36.8065', 'longitude' => '10.1815'],
            ['codigo' => 'SN', 'pais' => 'Senegal', 'nacionalidade' => 'Senegalesa', 'moeda' => 'XOF', 'capital' => 'Dacar', 'latitude' => '14.6928', 'longitude' => '-17.4467'],
            ['codigo' => 'ZW', 'pais' => 'Zimbábue', 'nacionalidade' => 'Zimbabuense', 'moeda' => 'ZWL', 'capital' => 'Harare', 'latitude' => '-17.8292', 'longitude' => '31.0522'],
            ['codigo' => 'EG', 'pais' => 'Egito', 'nacionalidade' => 'Egípcia', 'moeda' => 'EGP', 'capital' => 'Cairo', 'latitude' => '30.0444', 'longitude' => '31.2357'],
            ['codigo' => 'KR', 'pais' => 'Coreia do Sul', 'nacionalidade' => 'Sul-Coreana', 'moeda' => 'KRW', 'capital' => 'Seul', 'latitude' => '37.5665', 'longitude' => '126.9780'],
            ['codigo' => 'SA', 'pais' => 'Arábia Saudita', 'nacionalidade' => 'Saudita', 'moeda' => 'SAR', 'capital' => 'Riad', 'latitude' => '24.7136', 'longitude' => '46.6753'],
            ['codigo' => 'AF', 'pais' => 'Afeganistão', 'nacionalidade' => 'Afegã', 'moeda' => 'AFN', 'capital' => 'Cabul', 'latitude' => '34.5553', 'longitude' => '69.2075'],
            ['codigo' => 'AL', 'pais' => 'Albânia', 'nacionalidade' => 'Albanesa', 'moeda' => 'ALL', 'capital' => 'Tirana', 'latitude' => '41.3275', 'longitude' => '19.8189'],
            ['codigo' => 'DZ', 'pais' => 'Argélia', 'nacionalidade' => 'Argelina', 'moeda' => 'DZD', 'capital' => 'Argel', 'latitude' => '36.7372', 'longitude' => '3.0869'],
            ['codigo' => 'AD', 'pais' => 'Andorra', 'nacionalidade' => 'Andorrana', 'moeda' => 'EUR', 'capital' => 'Andorra-a-Velha', 'latitude' => '42.5078', 'longitude' => '1.5211'],
            ['codigo' => 'AM', 'pais' => 'Armênia', 'nacionalidade' => 'Armênia', 'moeda' => 'AMD', 'capital' => 'Yerevan', 'latitude' => '40.1792', 'longitude' => '44.4991'],
            ['codigo' => 'AT', 'pais' => 'Áustria', 'nacionalidade' => 'Austríaca', 'moeda' => 'EUR', 'capital' => 'Viena', 'latitude' => '48.2082', 'longitude' => '16.3738'],
            ['codigo' => 'AZ', 'pais' => 'Azerbaijão', 'nacionalidade' => 'Azeri', 'moeda' => 'AZN', 'capital' => 'Baku', 'latitude' => '40.4093', 'longitude' => '49.8671'],
            ['codigo' => 'BS', 'pais' => 'Bahamas', 'nacionalidade' => 'Bahamense', 'moeda' => 'BSD', 'capital' => 'Nassau', 'latitude' => '25.0343', 'longitude' => '-77.3963'],
            ['codigo' => 'BH', 'pais' => 'Bahrein', 'nacionalidade' => 'Bahrainita', 'moeda' => 'BHD', 'capital' => 'Manama', 'latitude' => '26.2235', 'longitude' => '50.5876'],
            ['codigo' => 'BD', 'pais' => 'Bangladesh', 'nacionalidade' => 'Bangladeshiana', 'moeda' => 'BDT', 'capital' => 'Daca', 'latitude' => '23.8103', 'longitude' => '90.4125'],
            ['codigo' => 'BY', 'pais' => 'Belarus', 'nacionalidade' => 'Bielorrussa', 'moeda' => 'BYN', 'capital' => 'Minsk', 'latitude' => '53.9006', 'longitude' => '27.5590'],
            ['codigo' => 'BE', 'pais' => 'Bélgica', 'nacionalidade' => 'Belga', 'moeda' => 'EUR', 'capital' => 'Bruxelas', 'latitude' => '50.8503', 'longitude' => '4.3517'],
            ['codigo' => 'BO', 'pais' => 'Bolívia', 'nacionalidade' => 'Boliviana', 'moeda' => 'BOB', 'capital' => 'Sucre', 'latitude' => '-19.0333', 'longitude' => '-65.2627'],
            ['codigo' => 'BA', 'pais' => 'Bósnia e Herzegovina', 'nacionalidade' => 'Bósnia', 'moeda' => 'BAM', 'capital' => 'Sarajevo', 'latitude' => '43.8563', 'longitude' => '18.4131'],
            ['codigo' => 'BW', 'pais' => 'Botsuana', 'nacionalidade' => 'Botsuanesa', 'moeda' => 'BWP', 'capital' => 'Gaborone', 'latitude' => '-24.6581', 'longitude' => '25.9122'],
            ['codigo' => 'KH', 'pais' => 'Camboja', 'nacionalidade' => 'Cambojana', 'moeda' => 'KHR', 'capital' => 'Phnom Penh', 'latitude' => '11.5564', 'longitude' => '104.9282'],
            ['codigo' => 'CM', 'pais' => 'Camarões', 'nacionalidade' => 'Camaronesa', 'moeda' => 'XAF', 'capital' => 'Yaoundé', 'latitude' => '3.8480', 'longitude' => '11.5021'],
            ['codigo' => 'KZ', 'pais' => 'Cazaquistão', 'nacionalidade' => 'Cazaque', 'moeda' => 'KZT', 'capital' => 'Astana', 'latitude' => '51.1694', 'longitude' => '71.4491'],
            ['codigo' => 'CL', 'pais' => 'Chile', 'nacionalidade' => 'Chilena', 'moeda' => 'CLP', 'capital' => 'Santiago', 'latitude' => '-33.4489', 'longitude' => '-70.6693'],
            ['codigo' => 'CO', 'pais' => 'Colômbia', 'nacionalidade' => 'Colombiana', 'moeda' => 'COP', 'capital' => 'Bogotá', 'latitude' => '4.7110', 'longitude' => '-74.0721'],
            ['codigo' => 'KP', 'pais' => 'Coreia do Norte', 'nacionalidade' => 'Norte-Coreana', 'moeda' => 'KPW', 'capital' => 'Pyongyang', 'latitude' => '39.0392', 'longitude' => '125.7625'],
            ['codigo' => 'CR', 'pais' => 'Costa Rica', 'nacionalidade' => 'Costarriquense', 'moeda' => 'CRC', 'capital' => 'San José', 'latitude' => '9.9281', 'longitude' => '-84.0907'],
            ['codigo' => 'HR', 'pais' => 'Croácia', 'nacionalidade' => 'Croata', 'moeda' => 'HRK', 'capital' => 'Zagreb', 'latitude' => '45.8150', 'longitude' => '15.9819'],
            ['codigo' => 'CU', 'pais' => 'Cuba', 'nacionalidade' => 'Cubana', 'moeda' => 'CUP', 'capital' => 'Havana', 'latitude' => '23.1136', 'longitude' => '-82.3666'],
            ['codigo' => 'DK', 'pais' => 'Dinamarca', 'nacionalidade' => 'Dinamarquesa', 'moeda' => 'DKK', 'capital' => 'Copenhague', 'latitude' => '55.6761', 'longitude' => '12.5683'],
            ['codigo' => 'DO', 'pais' => 'Dominica', 'nacionalidade' => 'Dominicana', 'moeda' => 'DOP', 'capital' => 'Roseau', 'latitude' => '15.3092', 'longitude' => '-61.3790'],
            ['codigo' => 'SV', 'pais' => 'El Salvador', 'nacionalidade' => 'Salvadorenha', 'moeda' => 'USD', 'capital' => 'San Salvador', 'latitude' => '13.6929', 'longitude' => '-89.2182'],
            ['codigo' => 'AE', 'pais' => 'Emirados Árabes Unidos', 'nacionalidade' => 'Emirati', 'moeda' => 'AED', 'capital' => 'Abu Dhabi', 'latitude' => '24.4539', 'longitude' => '54.3773'],
            ['codigo' => 'EC', 'pais' => 'Equador', 'nacionalidade' => 'Equatoriana', 'moeda' => 'USD', 'capital' => 'Quito', 'latitude' => '-0.1807', 'longitude' => '-78.4678'],
            ['codigo' => 'SK', 'pais' => 'Eslováquia', 'nacionalidade' => 'Eslovaca', 'moeda' => 'EUR', 'capital' => 'Bratislava', 'latitude' => '48.1486', 'longitude' => '17.1077'],
            ['codigo' => 'SI', 'pais' => 'Eslovênia', 'nacionalidade' => 'Eslovena', 'moeda' => 'EUR', 'capital' => 'Liubliana', 'latitude' => '46.0569', 'longitude' => '14.5058'],
            ['codigo' => 'ES', 'pais' => 'Espanha', 'nacionalidade' => 'Espanhola', 'moeda' => 'EUR', 'capital' => 'Madri', 'latitude' => '40.4165', 'longitude' => '-3.7026'],
            ['codigo' => 'EE', 'pais' => 'Estônia', 'nacionalidade' => 'Estoniana', 'moeda' => 'EUR', 'capital' => 'Tallinn', 'latitude' => '59.4370', 'longitude' => '24.7536'],
            ['codigo' => 'FI', 'pais' => 'Finlândia', 'nacionalidade' => 'Finlandesa', 'moeda' => 'EUR', 'capital' => 'Helsinque', 'latitude' => '60.1695', 'longitude' => '24.9355'],
            ['codigo' => 'GE', 'pais' => 'Geórgia', 'nacionalidade' => 'Georgiana', 'moeda' => 'GEL', 'capital' => 'Tbilisi', 'latitude' => '41.7151', 'longitude' => '44.8271'],
            ['codigo' => 'GR', 'pais' => 'Grécia', 'nacionalidade' => 'Grega', 'moeda' => 'EUR', 'capital' => 'Atenas', 'latitude' => '37.9838', 'longitude' => '23.7275'],
            ['codigo' => 'GT', 'pais' => 'Guatemala', 'nacionalidade' => 'Guatemalteca', 'moeda' => 'GTQ', 'capital' => 'Cidade da Guatemala', 'latitude' => '14.6349', 'longitude' => '-90.5069'],
            ['codigo' => 'GN', 'pais' => 'Guiné', 'nacionalidade' => 'Guineense', 'moeda' => 'GNF', 'capital' => 'Conacri', 'latitude' => '9.6412', 'longitude' => '-13.5784'],
            ['codigo' => 'HN', 'pais' => 'Honduras', 'nacionalidade' => 'Hondurenha', 'moeda' => 'HNL', 'capital' => 'Tegucigalpa', 'latitude' => '14.0723', 'longitude' => '-87.1921'],
            ['codigo' => 'HU', 'pais' => 'Hungria', 'nacionalidade' => 'Húngara', 'moeda' => 'HUF', 'capital' => 'Budapeste', 'latitude' => '47.4979', 'longitude' => '19.0402'],
            ['codigo' => 'ID', 'pais' => 'Indonésia', 'nacionalidade' => 'Indonésia', 'moeda' => 'IDR', 'capital' => 'Jacarta', 'latitude' => '-6.2088', 'longitude' => '106.8456'],
            ['codigo' => 'IR', 'pais' => 'Irã', 'nacionalidade' => 'Iraniana', 'moeda' => 'IRR', 'capital' => 'Teerã', 'latitude' => '35.6892', 'longitude' => '51.3890'],
            ['codigo' => 'IQ', 'pais' => 'Iraque', 'nacionalidade' => 'Iraquiana', 'moeda' => 'IQD', 'capital' => 'Bagdá', 'latitude' => '33.3152', 'longitude' => '44.3661'],
            ['codigo' => 'IE', 'pais' => 'Irlanda', 'nacionalidade' => 'Irlandesa', 'moeda' => 'EUR', 'capital' => 'Dublin', 'latitude' => '53.3498', 'longitude' => '-6.2603'],
            ['codigo' => 'IS', 'pais' => 'Islândia', 'nacionalidade' => 'Islandesa', 'moeda' => 'ISK', 'capital' => 'Reykjavik', 'latitude' => '64.1466', 'longitude' => '-21.9426'],
            ['codigo' => 'IL', 'pais' => 'Israel', 'nacionalidade' => 'Israelense', 'moeda' => 'ILS', 'capital' => 'Jerusalém', 'latitude' => '31.7683', 'longitude' => '35.2137'],
            ['codigo' => 'JM', 'pais' => 'Jamaica', 'nacionalidade' => 'Jamaicana', 'moeda' => 'JMD', 'capital' => 'Kingston', 'latitude' => '18.0179', 'longitude' => '-76.8099'],
            ['codigo' => 'JO', 'pais' => 'Jordânia', 'nacionalidade' => 'Jordaniana', 'moeda' => 'JOD', 'capital' => 'Amã', 'latitude' => '31.9539', 'longitude' => '35.9106'],
            ['codigo' => 'KW', 'pais' => 'Kuwait', 'nacionalidade' => 'Kuwaitiana', 'moeda' => 'KWD', 'capital' => 'Cidade do Kuwait', 'latitude' => '29.3759', 'longitude' => '47.9774'],
            ['codigo' => 'LA', 'pais' => 'Laos', 'nacionalidade' => 'Laociana', 'moeda' => 'LAK', 'capital' => 'Vientiane', 'latitude' => '17.9757', 'longitude' => '102.6331'],
            ['codigo' => 'LV', 'pais' => 'Letônia', 'nacionalidade' => 'Letã', 'moeda' => 'EUR', 'capital' => 'Riga', 'latitude' => '56.9496', 'longitude' => '24.1052'],
            ['codigo' => 'LB', 'pais' => 'Líbano', 'nacionalidade' => 'Libanesa', 'moeda' => 'LBP', 'capital' => 'Beirute', 'latitude' => '33.8886', 'longitude' => '35.4955'],
            ['codigo' => 'LY', 'pais' => 'Líbia', 'nacionalidade' => 'Líbia', 'moeda' => 'LYD', 'capital' => 'Trípoli', 'latitude' => '32.8872', 'longitude' => '13.1913'],
            ['codigo' => 'LT', 'pais' => 'Lituânia', 'nacionalidade' => 'Lituana', 'moeda' => 'EUR', 'capital' => 'Vilnius', 'latitude' => '54.6872', 'longitude' => '25.2797'],
            ['codigo' => 'LU', 'pais' => 'Luxemburgo', 'nacionalidade' => 'Luxemburguesa', 'moeda' => 'EUR', 'capital' => 'Cidade de Luxemburgo', 'latitude' => '49.6117', 'longitude' => '6.1319'],
            ['codigo' => 'MY', 'pais' => 'Malásia', 'nacionalidade' => 'Malaia', 'moeda' => 'MYR', 'capital' => 'Kuala Lumpur', 'latitude' => '3.1390', 'longitude' => '101.6869'],
            ['codigo' => 'MW', 'pais' => 'Malawi', 'nacionalidade' => 'Malauiana', 'moeda' => 'MWK', 'capital' => 'Lilongwe', 'latitude' => '-13.9626', 'longitude' => '33.7741'],
            ['codigo' => 'MT', 'pais' => 'Malta', 'nacionalidade' => 'Maltês', 'moeda' => 'EUR', 'capital' => 'Valeta', 'latitude' => '35.8997', 'longitude' => '14.5146'],
            ['codigo' => 'MA', 'pais' => 'Marrocos', 'nacionalidade' => 'Marroquina', 'moeda' => 'MAD', 'capital' => 'Rabat', 'latitude' => '34.0209', 'longitude' => '-6.8416'],
            ['codigo' => 'MC', 'pais' => 'Mônaco', 'nacionalidade' => 'Monegasca', 'moeda' => 'EUR', 'capital' => 'Mônaco', 'latitude' => '43.7333', 'longitude' => '7.4167'],
            ['codigo' => 'MN', 'pais' => 'Mongólia', 'nacionalidade' => 'Mongol', 'moeda' => 'MNT', 'capital' => 'Ulaanbaatar', 'latitude' => '47.8864', 'longitude' => '106.9057'],
            ['codigo' => 'ME', 'pais' => 'Montenegro', 'nacionalidade' => 'Montenegrina', 'moeda' => 'EUR', 'capital' => 'Podgorica', 'latitude' => '42.4304', 'longitude' => '19.2594'],
            ['codigo' => 'MM', 'pais' => 'Myanmar', 'nacionalidade' => 'Birmanesa', 'moeda' => 'MMK', 'capital' => 'Naypyidaw', 'latitude' => '19.7633', 'longitude' => '96.0785'],
            ['codigo' => 'NA', 'pais' => 'Namíbia', 'nacionalidade' => 'Namibiana', 'moeda' => 'NAD', 'capital' => 'Windhoek', 'latitude' => '-22.5590', 'longitude' => '17.0832'],
            ['codigo' => 'NP', 'pais' => 'Nepal', 'nacionalidade' => 'Nepalesa', 'moeda' => 'NPR', 'capital' => 'Catmandu', 'latitude' => '27.7172', 'longitude' => '85.3240'],
            ['codigo' => 'NZ', 'pais' => 'Nova Zelândia', 'nacionalidade' => 'Neozelandesa', 'moeda' => 'NZD', 'capital' => 'Wellington', 'latitude' => '-41.2865', 'longitude' => '174.7762'],
            ['codigo' => 'OM', 'pais' => 'Omã', 'nacionalidade' => 'Omanense', 'moeda' => 'OMR', 'capital' => 'Mascate', 'latitude' => '23.5880', 'longitude' => '58.3829'],
            ['codigo' => 'PK', 'pais' => 'Paquistão', 'nacionalidade' => 'Paquistanesa', 'moeda' => 'PKR', 'capital' => 'Islamabad', 'latitude' => '33.6844', 'longitude' => '73.0479'],
            ['codigo' => 'PA', 'pais' => 'Panamá', 'nacionalidade' => 'Panamenha', 'moeda' => 'PAB', 'capital' => 'Cidade do Panamá', 'latitude' => '8.9824', 'longitude' => '-79.5199'],
            ['codigo' => 'PY', 'pais' => 'Paraguai', 'nacionalidade' => 'Paraguaia', 'moeda' => 'PYG', 'capital' => 'Assunção', 'latitude' => '-25.2637', 'longitude' => '-57.5759'],
            ['codigo' => 'PE', 'pais' => 'Peru', 'nacionalidade' => 'Peruana', 'moeda' => 'PEN', 'capital' => 'Lima', 'latitude' => '-12.0464', 'longitude' => '-77.0428'],
            ['codigo' => 'PL', 'pais' => 'Polônia', 'nacionalidade' => 'Polonesa', 'moeda' => 'PLN', 'capital' => 'Varsóvia', 'latitude' => '52.2297', 'longitude' => '21.0122'],
            ['codigo' => 'PT', 'pais' => 'Portugal', 'nacionalidade' => 'Portuguesa', 'moeda' => 'EUR', 'capital' => 'Lisboa', 'latitude' => '38.7223', 'longitude' => '-9.1393'],
            ['codigo' => 'QA', 'pais' => 'Qatar', 'nacionalidade' => 'Qatariana', 'moeda' => 'QAR', 'capital' => 'Doha', 'latitude' => '25.2760', 'longitude' => '51.2265'],
            ['codigo' => 'RO', 'pais' => 'Romênia', 'nacionalidade' => 'Romena', 'moeda' => 'RON', 'capital' => 'Bucareste', 'latitude' => '44.4268', 'longitude' => '26.1025'],
            ['codigo' => 'RS', 'pais' => 'Sérvia', 'nacionalidade' => 'Sérvia', 'moeda' => 'RSD', 'capital' => 'Belgrado', 'latitude' => '44.7866', 'longitude' => '20.4489'],
            ['codigo' => 'SG', 'pais' => 'Singapura', 'nacionalidade' => 'Singapurense', 'moeda' => 'SGD', 'capital' => 'Singapura', 'latitude' => '1.3521', 'longitude' => '103.8198'],
            ['codigo' => 'LK', 'pais' => 'Sri Lanka', 'nacionalidade' => 'Cingalesa', 'moeda' => 'LKR', 'capital' => 'Sri Jayawardenepura Kotte', 'latitude' => '6.9271', 'longitude' => '79.8612'],
            ['codigo' => 'SE', 'pais' => 'Suécia', 'nacionalidade' => 'Sueca', 'moeda' => 'SEK', 'capital' => 'Estocolmo', 'latitude' => '59.3293', 'longitude' => '18.0686'],
            ['codigo' => 'CH', 'pais' => 'Suíça', 'nacionalidade' => 'Suíça', 'moeda' => 'CHF', 'capital' => 'Berna', 'latitude' => '46.9481', 'longitude' => '7.4474'],
            ['codigo' => 'SY', 'pais' => 'Síria', 'nacionalidade' => 'Síria', 'moeda' => 'SYP', 'capital' => 'Damasco', 'latitude' => '33.5138', 'longitude' => '36.2765'],
            ['codigo' => 'TJ', 'pais' => 'Tadjiquistão', 'nacionalidade' => 'Tadjiquistanesa', 'moeda' => 'TJS', 'capital' => 'Duchambé', 'latitude' => '38.5598', 'longitude' => '68.7870'],
            ['codigo' => 'TH', 'pais' => 'Tailândia', 'nacionalidade' => 'Tailandesa', 'moeda' => 'THB', 'capital' => 'Bangkok', 'latitude' => '13.7563', 'longitude' => '100.5018'],
            ['codigo' => 'TL', 'pais' => 'Timor-Leste', 'nacionalidade' => 'Timorense', 'moeda' => 'USD', 'capital' => 'Díli', 'latitude' => '-8.5569', 'longitude' => '125.5603'],
            ['codigo' => 'TG', 'pais' => 'Togo', 'nacionalidade' => 'Togolesa', 'moeda' => 'XOF', 'capital' => 'Lomé', 'latitude' => '6.1725', 'longitude' => '1.2314'],
            ['codigo' => 'TT', 'pais' => 'Trinidad e Tobago', 'nacionalidade' => 'Trinitária', 'moeda' => 'TTD', 'capital' => 'Porto de Espanha', 'latitude' => '10.6918', 'longitude' => '-61.2225'],
            ['codigo' => 'TR', 'pais' => 'Turquia', 'nacionalidade' => 'Turca', 'moeda' => 'TRY', 'capital' => 'Ancara', 'latitude' => '39.9334', 'longitude' => '32.8597'],
            ['codigo' => 'TM', 'pais' => 'Turcomenistão', 'nacionalidade' => 'Turcomena', 'moeda' => 'TMT', 'capital' => 'Ashgabat', 'latitude' => '37.9601', 'longitude' => '58.3261'],
            ['codigo' => 'UA', 'pais' => 'Ucrânia', 'nacionalidade' => 'Ucraniana', 'moeda' => 'UAH', 'capital' => 'Kiev', 'latitude' => '50.4501', 'longitude' => '30.5234'],
            ['codigo' => 'UY', 'pais' => 'Uruguai', 'nacionalidade' => 'Uruguaia', 'moeda' => 'UYU', 'capital' => 'Montevidéu', 'latitude' => '-34.9011', 'longitude' => '-56.1645'],
            ['codigo' => 'UZ', 'pais' => 'Uzbequistão', 'nacionalidade' => 'Uzbeque', 'moeda' => 'UZS', 'capital' => 'Tashkent', 'latitude' => '41.2995', 'longitude' => '69.2401'],
            ['codigo' => 'VA', 'pais' => 'Vaticano', 'nacionalidade' => 'Vaticana', 'moeda' => 'EUR', 'capital' => 'Vaticano', 'latitude' => '41.9029', 'longitude' => '12.4534'],
            ['codigo' => 'VE', 'pais' => 'Venezuela', 'nacionalidade' => 'Venezuelana', 'moeda' => 'VES', 'capital' => 'Caracas', 'latitude' => '10.4806', 'longitude' => '-66.9036'],
            ['codigo' => 'VN', 'pais' => 'Vietnã', 'nacionalidade' => 'Vietnamita', 'moeda' => 'VND', 'capital' => 'Hanói', 'latitude' => '21.0285', 'longitude' => '105.8542'],
            ['codigo' => 'ZM', 'pais' => 'Zâmbia', 'nacionalidade' => 'Zambiana', 'moeda' => 'ZMW', 'capital' => 'Lusaca', 'latitude' => '-15.3875', 'longitude' => '28.3228'],
        ]);
        
    }
}
